import { CropProfile, CropType } from '@/types/agrivoltaics';

export const CROP_PROFILES: Record<CropType, CropProfile> = {
  lettuce: {
    id: 'lettuce',
    name: 'Lettuce (Butterhead / Romaine)',
    targetDLI: 14,
    minDLI: 12,
    maxDLI: 16,
    shadeTolerance: 'High',
    baseWaterReqLiters: 120,
    description: 'Shade-tolerant leafy green. Retains crispness & prevents bolting under PV panel arrays.',
    parSensitivity: 0.85,
  },
  spinach: {
    id: 'spinach',
    name: 'Spinach (Baby Leaf)',
    targetDLI: 12,
    minDLI: 10,
    maxDLI: 15,
    shadeTolerance: 'High',
    baseWaterReqLiters: 110,
    description: 'Thrives in partial solar shade with minimal transpiration loss.',
    parSensitivity: 0.80,
  },
  tomatoes: {
    id: 'tomatoes',
    name: 'Tomatoes (Vine Ripe)',
    targetDLI: 25,
    minDLI: 20,
    maxDLI: 30,
    shadeTolerance: 'Low',
    baseWaterReqLiters: 220,
    description: 'High light requirement crop. Requires dynamic tracking to prevent yield reduction.',
    parSensitivity: 1.30,
  },
  strawberries: {
    id: 'strawberries',
    name: 'Strawberries (June-Bearing)',
    targetDLI: 18,
    minDLI: 16,
    maxDLI: 20,
    shadeTolerance: 'Medium',
    baseWaterReqLiters: 160,
    description: 'Benefits from midday microclimate temperature suppression, extending harvest window.',
    parSensitivity: 1.00,
  },
  berries: {
    id: 'berries',
    name: 'Blueberries / Bush Berries',
    targetDLI: 18,
    minDLI: 15,
    maxDLI: 22,
    shadeTolerance: 'Medium',
    baseWaterReqLiters: 180,
    description: 'Perennial bush crop responsive to partial shading during peak summer heatwaves.',
    parSensitivity: 1.05,
  },
};
